spring.application.name=PresentationLayer
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/inintr00383/Documents/SpringBootCourse/module-2/EmployeeDb
spring.datasource.username=liki
spring.datasource.password=liki@123
spring.jpa.hibernate.ddl-auto=update
